### ISSUE TITLE
Error processing YAML, it's likely the original YAML is not valid when using valid YAML pipeline

### ISSUE THREAD

**Issue by tomaustin700** [samsmithnz/AzurePipelinesToGitHubActionsConverter#149]
**Describe the bug**
Error generated when processing a valid pipeline

**To Reproduce**
1. Go to https://pipelinestoactions.azurewebsites.net/
2. Enter the following yaml pipeline

```
name: PRBuild_$(Year:yy)$(DayOfYear)$(Rev:.r)
trigger: none

stages:
- stage: Stage
  jobs:
  - job: "Job"
    workspace:
      clean: all

    pool:
      name: PoolName
    steps:
    - task: PowerShell@1
      displayName: 'Script'
      inputs:
        scriptName: 'Script.ps1'
```

**Expected behavior**
Should convert

**Screenshots**
![image](https://user-images.githubusercontent.com/6324102/90607075-a1beda80-e1f8-11ea-8427-ba5a0456e540.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version 84

**Additional context**
Definitely a valid pipeline, validates fine when using yamlpipelinesvalidator.dev

Full callstack
```
Error processing YAML, it's likely the original YAML is not valid
Original error message: YamlDotNet.Core.YamlException: (Line: 2, Col: 10, Idx: 56) - (Line: 2, Col: 14, Idx: 60): Exception during deserialization
 ---> System.InvalidCastException: Invalid cast from 'System.String' to 'AzurePipelinesToGitHubActionsConverter.Core.AzurePipelines.Trigger'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at YamlDotNet.Serialization.Utilities.TypeConverter.ChangeType(Object value, Type destinationType, CultureInfo culture)
   at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at AzurePipelinesToGitHubActionsConverter.Core.Conversion.Serialization.GenericObjectSerialization.DeserializeYaml[T](String yaml)
   at AzurePipelinesToGitHubActionsConverter.Core.Conversion.Conversion.ConvertAzurePipelineToGitHubAction(String input)
   at PipelinesToActionsWeb.Controllers.HomeController.ProcessConversion(String input) in D:\a\AzurePipelinesToGitHubActionsConverterWeb\AzurePipelinesToGitHubActionsConverterWeb\PipelinesToActions\PipelinesToActions\Controllers\HomeController.cs:line 81
```

**Comment by samsmithnz** [comment]
Thanks for your contribution. I need to review the schema to see why this is failing. I'm curious about why you have workspace: clean in there. Is that solving a specific issue? You don't normally need it.

**Comment by tomaustin700** [comment]
Hi @samsmithnz. No specific reason for the clean, I can't actually remember why it's there.

**Comment by samsmithnz** [comment]
I don't believe it's causing the issue, but wanted to highlight it as a simplification of your current yaml. I'm planning to review yours later today.

**Comment by f2calv** [comment]
If you are running your builds on a self-hosted agent (as I do) the clean is important. On a Microsoft-hosted agent the VM is new'd up every time a build happens, on a self-hosted agent it isn't - so you risk having random artifacts from previous builds getting mixed up with the current build.

**Comment by tomaustin700** [comment]
We are using self-hosted agents so that would make sense as to why we have the clean. I think when I migrated a lot of our pipelines from classic to YAML I copied them like-for-like also.

**Comment by samsmithnz** [comment]
Here are the docs are here explaining the clean, for reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#workspace

**Comment by samsmithnz** [comment]
The issue was the trigger: none statement. I have a fix I'm pushing out shortly. There isn't an equivalent in GitHub yet, so it translates to:

```
on:
  push:
    branches:
    - none
```
