### ISSUE TITLE
Error "Stack empty" thrown when processing YAML

### ISSUE THREAD

**Issue by johlju** [samsmithnz/AzurePipelinesToGitHubActionsConverter#150]
**Describe the bug**
Got an error when processing YAML.

```
Unexpected error: System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Pop()
   at AzurePipelinesToGitHubActionsConverter.Core.Conversion.ConditionsProcessing.Nested(String value)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AzurePipelinesToGitHubActionsConverter.Core.Conversion.ConditionsProcessing.FindBracketedContentsInString(String text)
   at AzurePipelinesToGitHubActionsConverter.Core.Conversion.ConditionsProcessing.TranslateConditions(String condition)
   at AzurePipelinesToGitHubActionsConverter.Core.Conversion.ConditionsProcessing.TranslateConditions(String condition)
   at AzurePipelinesToGitHubActionsConverter.Core.Conversion.PipelineProcessing`2.ProcessIndividualJob(Job job, Resources resources)
   at AzurePipelinesToGitHubActionsConverter.Core.Conversion.PipelineProcessing`2.ProcessJobs(Job[] jobs, Resources resources)
   at AzurePipelinesToGitHubActionsConverter.Core.Conversion.PipelineProcessing`2.ProcessPipeline(AzurePipelinesRoot`2 azurePipeline, String[] simpleTrigger, Trigger complexTrigger, Dictionary`2 simpleVariables, Variable[] complexVariables)
   at AzurePipelinesToGitHubActionsConverter.Core.Conversion.Conversion.ConvertAzurePipelineToGitHubAction(String input)
   at PipelinesToActionsWeb.Controllers.HomeController.ProcessConversion(String input) in D:\a\AzurePipelinesToGitHubActionsConverterWeb\AzurePipelinesToGitHubActionsConverterWeb\PipelinesToActions\PipelinesToActions\Controllers\HomeController.cs:line 81
                    
```

**To Reproduce**
Pasted in the pipeline config here; https://github.com/dsccommunity/SqlServerDsc/blob/master/azure-pipelines.yml

**Expected behavior**
No error to be thrown. ;)

**Screenshots**
N/a

**Desktop (please complete the following information):**
 - OS: WIndows 10 Insider
 - Browser: Edge
 - Version: 84.0.522.61 (Official build) (64-bit)

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by johlju** [comment]
Same issue occurs in Chrome 84.0.4147.125 (Official Build) (64-bit).

**Comment by samsmithnz** [comment]
Thank you so much for contributing and helping to make this product better. The error is related to a multi-line condition. 

```
    condition: |
      and(
        succeeded(),
        or(
          eq(variables['Build.SourceBranch'], 'refs/heads/master'),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        ),
        contains(variables['System.TeamFoundationCollectionUri'], 'dsccommunity')
      )
```

I'll see if I can fix it soon.

**Comment by samsmithnz** [comment]
The root cause of this error is related to the RegEx I use to split the condition - which turns out can't handle nested conditions beyond 2 levels deep (this is 3). Guess how many levels my unit tests cover... 

The solution is to create my own parser... Trying to find some code so I don't have to start from scratch. Sounds fun. :)
